version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        # Pass production VITE_ variables as build arguments
        # These should match the ARG declarations in Dockerfile.prod
        # Get these values from a secure place or a .env.prod file (gitignored)
        VITE_API_URL: "https://aiwaverider.com/api" # IMPORTANT: Your actual prod backend URL
      env_file:
        - .env.production # Load production environment variables
    container_name: frontend_prod
    ports:
      - "80:80" # Map container's port 80 (Nginx) to host's port 80
      # Or use a different host port if 80 is taken: e.g., "5174:80"
    restart: unless-stopped
    networks:
      - app_network_frontend_prod

networks:
  app_network_frontend_prod:
    driver: bridge